version: "3.9"

services:
  web:
    image: ghcr.io/teampass/teampass-web:latest
    container_name: teampass-web
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - php
      - db
  php:
    image: ghcr.io/teampass/teampass-php:latest
    container_name: teampass-php
    volumes:
      - ./data/app-logs:/app/Data/Logs
    restart: always
    depends_on:
      - db
    environment:
      FLOW_DB_HOST: db:3306
      FLOW_DB_USER: teampass
      FLOW_DB_PASSWORD: teampass
      FLOW_DB_NAME: teampass
  db:
    image: mysql:5.7
    container_name: teampass-mysql
    volumes:
      - ./data/db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teampass
      MYSQL_USER: teampass
      MYSQL_PASSWORD: teampass
  db-backup:
    image: databack/mysql-backup
    container_name: teampass-mysql-backup
    restart: always
    user: "0"
    volumes:
      - ./data/db-backups:/db
      - ./assets/secure.sh:/scripts.d/post-backup/secure.sh
    environment:
      DB_DUMP_TARGET: /db
      DB_USER: root
      DB_PASS: root
      DB_NAMES: teampass
      DB_DUMP_FREQ: 5
      DB_DUMP_BEGIN: +3
      DB_SERVER: db
      ENCKEY: <enter-encryption-key>
      DB_DUMP_SAFECHARS: 1
    depends_on:
      - db
